#!/usr/bin/env bash

echo "User manager simulator!"
PS3='Please enter your choice: '
who=$(who -u | grep tty | cut -d " " -f1)
options=('Backup home' 'Delete user' 'Unlog user' 'Quit')
select opt in "${options[@]}"
do
case $opt in
"Backup home")
echo "which home do you want to backup (the home will be saved in : /home/$who/):"
read backup
output=$(cat /etc/passwd | grep -o $backup)
if [ -z "$output" ]
then
	echo "nothing to backup"
else
	cp -r /home/$backup  /home/$who/
	echo "backup done!"
fi
;;
"Delete user")
echo "Who do you want to delete ?"
read target
output=$(cat /etc/passwd | grep -o $target)
if [ -z "$target" ]
then
	echo "User doesn't exist"
else
	echo "Deleting user..."
	killall -KILL -u $target
	deluser --remove-home $target
	echo "Done!"
fi
;;
"Unlog user")
echo "who do you want to unlog ?"
read u
killall -KILL -u $u
echo "Done!"
;;
"Quit")
break
;;
*) echo "invalid option $REPLY";;
esac
done
